config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    unlocks: "users/unlocks"
  }
  devise_for :students, path: 'students', controllers: {
    sessions: "students/sessions",
    registrations: "students/registrations",
    confirmations: "students/confirmations",
    passwords: "students/passwords",
    unlocks: "students/unlocks"
  }
  root to: 'pages#home'
  resources :tickets, only: [:index, :new, :create, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Tickets", tickets_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown d-flex align-items-center justify-content-center">
          <div class="ml-4" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-labelledby="navbarDropdown" style="font-size: 26px;">
            <i class="fas fa-user dropdown-toggle"></i>
          </div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% elsif student_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Tickets", tickets_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Nouveau Ticket", new_ticket_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <div class="ml-4" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-labelledby="navbarDropdown" style="font-size: 26px;">
            <i class="fas fa-user dropdown-toggle"></i>
          </div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Déconnexion", destroy_student_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Professeur Log-in", new_user_session_path, class: "text-white nav-link btn btn-secondary mr-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "Étudiant Log-in", new_student_session_path, class: "text-white nav-link btn btn-primary" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>