config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    unlocks: "users/unlocks"
  }
  devise_for :students, path: 'students', controllers: {
    sessions: "students/sessions",
    registrations: "students/registrations",
    confirmations: "students/confirmations",
    passwords: "students/passwords",
    unlocks: "students/unlocks"
  }
  root to: 'pages#home'
  resources :tickets, only: [:index, :new, :create, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :student
  enum state: ["pending", "finished"]
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :index, :create]

  def index
    if current_user
      @tickets = Ticket.where(user_id: current_user.id).where(state: "pending").order(created_at: :asc)
    else
      @tickets = Ticket.where(user_id: current_student.user_id).where(state: "pending").order(created_at: :asc)
    end
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.pending!
    @ticket.save
    redirect_to tickets_path
  end

  def update
    @ticket = Ticket.find(params[:id])
    @ticket.finished!
    @ticket.save
    redirect_to tickets_path
  end

  private

  def ticket_params
    params.require(:ticket).permit(:user_id, :student_id, :message)
  end
end

app/views/tickets/edit.html.erb
<h1>Tickets#edit</h1>
<p>Find me in app/views/tickets/edit.html.erb</p>

app/views/tickets/index.html.erb
<div class="container">
  <h1 class="text-center mt-3">Liste des tickets actifs</h1>
  <p class="text-center">Plus votre ticket est haut plus tôt ça sera votre tour !</p>
  <% if current_student %>
    <div id="student-refresh"></div>
  <% end %>
  <div class="d-flex flex-column">
    <% if @tickets.empty? %>
      <h3>Aucun ticket pour le moment, le prof peut se reposer 😜</h3>
    <% end %>
    <% @tickets.each do |ticket| %>
      <div class="d-flex justify-content-around align-items-center border rounded border-dark p-3 mb-3">
        <p>
          Message : <%= ticket.message %>
        </p>
        <p>
          De : <%= ticket.student.name%>
        </p>
        <p>
          Groupe : <%= ticket.student.group_name %>
        </p>
        <% if current_user %>
          <%= link_to "Ticket terminé", ticket_path(ticket), method: :put, class: "btn btn-primary" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/tickets/new.html.erb
<h1>Créer un ticket</h1>
<p>Expliquez le contexte du ticket, le nom du professeur et votre ticket s'affichera dans la file d'attente</p>

<%= simple_form_for @ticket do |f| %>
  <%= f.input :message %>
  <%= f.input :student_id, as: :hidden, input_html: { value: current_student.id } %>
  <%= f.input :user_id, as: :hidden, input_html: { value: current_student.user.id } %>
  <%= f.button :submit %>
<% end %>